# Generated by Django 3.0 on 2019-12-06 07:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='amount',
            field=models.DecimalField(decimal_places=10, default=1, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trade',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='price',
            field=models.DecimalField(decimal_places=10, default=1, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trade',
            name='trade_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 12, 6, 7, 5, 35, 534587, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trade',
            name='value',
            field=models.DecimalField(decimal_places=10, default=1, max_digits=20),
            preserve_default=False,
        ),
    ]
