# Generated by Django 2.2.8 on 2019-12-19 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0001_initial'),
        ('trade', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='trade',
            unique_together={('exchange', 'symbol', 'trade_time')},
        ),
    ]
