# Generated by Django 2.2.8 on 2019-12-19 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2048)),
                ('description', models.TextField(blank=True, max_length=100000)),
                ('url', models.URLField(blank=True)),
                ('symbol_format', models.CharField(choices=[('LOWERCASE', 'LOWERCASE'), ('UPPERCASE', 'UPPERCASE'), ('LOWER_HYPHEN', 'LOWER_HYPHEN'), ('UPPER_HYPHEN', 'UPPER_HYPHEN'), ('LOWER_UNDERSCORE', 'LOWER_UNDERSCORE'), ('UPPER_UNDERSCORE', 'UPPER_UNDERSCORE')], default='UPPER_UNDERSCORE', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base', models.CharField(max_length=1024)),
                ('quote', models.CharField(max_length=1024)),
            ],
        ),
    ]
