# Generated by Django 3.0 on 2019-12-06 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
