# Generated by Django 3.0 on 2019-12-06 06:46

from django.db import migrations, models
import exchange.models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0002_auto_20191206_0635'),
    ]

    operations = [
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base', models.CharField(max_length=1024)),
                ('quote', models.CharField(max_length=1024)),
            ],
        ),
        migrations.AddField(
            model_name='exchange',
            name='symbol_type',
            field=models.CharField(choices=[('LOWERCASE', 'LOWERCASE'), ('UPPERCASE', 'UPPERCASE'), ('LOWER_HYPHEN', 'LOWER_HYPHEN'), ('UPPER_HYPHEN', 'UPPER_HYPHEN'), ('LOWER_UNDERSCORE', 'LOWER_UNDERSCORE'), ('UPPER_UNDERSCORE', 'UPPER_UNDERSCORE')], default=exchange.models.SymbolFormatEnum['UPPER_UNDERSCORE'], max_length=128),
        ),
    ]
