# Generated by Django 2.2.8 on 2019-12-18 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0004_auto_20191206_0705'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exchange',
            old_name='symbol_type',
            new_name='symbol_format',
        ),
    ]
